---
name: nokogiri
version: '1.11'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 6f9f54a753a78c505e63e7f31a48b3f71f1b510d
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
